[package]
name = "yew-color-picker"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
web-sys = { version = "0.3.56", features = [
  "DomRect",
  "Element",
  "ResizeObserver",
]}
wgpu = "0.12.0"
yew = "0.19.3"
