[workspace]
resolver = "2"
members = [
  "step-runtime",
  "web-prototype",
  "yew-components/yew-wgpu",
  "yew-components/yew-color-picker",
  "yew-wgpu-web-prototype",
]

[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true
