[config]
default_to_workspace = false
load_cargo_aliases = false
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true
time_summary = true


[tasks.clean]
script_runner="@duckscript"
script = "rm -r dist"
category = "Build"


[tasks.build-yew-app]
command = "wasm-pack"
args = [
  "build",
  "yew-wgpu-web-prototype",
  "--target",
  "web",
  "--no-typescript",
  "--out-dir",
  "../tmp",
  "--out-name",
  "entry",
  "--release",
]
private = true
category = "Build"

[tasks.copy-wasm]
script_runner="@duckscript"
script = "glob_cp tmp/*.wasm dist"
private = true
category = "Build"

[tasks.copy-js]
script_runner="@duckscript"
script = "glob_cp tmp/*.js dist"
private = true
category = "Build"

[tasks.copy-css]
script_runner="@duckscript"
script = "glob_cp target/wasm32-unknown-unknown/release/*.css dist"
private = true
category = "Build"

[tasks.clean-tmp-directory]
script_runner="@duckscript"
script = "rm -r tmp"
private = true
category = "Build"

[tasks.build-rust]
category = "Build"
private = true
[tasks.build-rust.run_task]
name = ["build-yew-app", "copy-js", "copy-wasm", "copy-css", "clean-tmp-directory"]


[tasks.copy-asset-css]
script_runner="@duckscript"
script = "glob_cp yew-wgpu-web-prototype/**/*.css dist"
private = true


[tasks.copy-html]
script_runner="@duckscript"
script = "glob_cp yew-wgpu-web-prototype/**/*.html dist"
private = true
category = "Build"


[tasks.build-files]
run_task = { name = ["build-rust", "copy-asset-css", "copy-html"], parallel = true }
private = true
category = "Build"


[tasks.watch-rust]
script = """
npx -c "chokidar \"**/*.rs\" -c \\"cargo make --allow-private build-rust\\""
"""
private = true
category = "Build"

[tasks.watch-wgsl]
script = """
npx -c "chokidar \"**/*.wgsl\" -c \\"cargo make --allow-private build-rust\\""
"""
private = true
category = "Build"

[tasks.watch-asset-css]
script = """
npx -c "chokidar \"yew-wgpu-web-prototype/**/*.css\" -c \\"cargo make --allow-private copy-asset-css\\""
"""
private = true
category = "Build"

[tasks.watch-html]
script = """
npx -c "chokidar \"yew-wgpu-web-prototype/**/*.html\" -c \\"cargo make --allow-private copy-html\\""
"""
private = true
category = "Build"

[tasks.watch]
category = "Build"
[tasks.watch.run_task]
name = ["watch-rust", "watch-wgsl", "watch-asset-css", "watch-html"]
parallel = true


[tasks.start-server]
script = """
npx -c "browser-sync start -s dist -f dist -w --index ./index.html --port 80 --no-open"
"""
private = true
category = "Build"

[tasks.start-watch-serve]
private = true
category = "Build"
[tasks.start-watch-serve.run_task]
name = ["watch", "start-server"]
parallel = true

[tasks.serve]
category = "Build"
[tasks.serve.run_task]
name = ["build", "start-watch-serve"]


[tasks.build]
category = "Build"
[tasks.build.run_task]
name = ["clean", "build-files"]


[tasks.default]
dependencies = ["build"]
category = "Build"
