[config]
default_to_workspace = false

[tasks.yew]
command = "trunk"
args = [
  "serve",
  "yew-wgpu-web-prototype/index.html",
  "-d",
  "dist",
  "--release",
  "--port",
  "80",
]
env = { RUSTFLAGS = "--cfg=web_sys_unstable_apis" }

[tasks.yew-build]
command = "trunk"
args = [
  "build",
  "yew-wgpu-web-prototype/index.html",
  "-d",
  "dist",
  "--release",
]
env = { RUSTFLAGS = "--cfg=web_sys_unstable_apis" }

[tasks.build]
command = "wasm-pack"
args = [
  "build",
  "yew-wgpu-web-prototype",
  "--target",
  "web",
  "--no-typescript",
  "--out-dir",
  "../out",
  "--out-name",
  "index",
  "--release",
]
